# Generated by Django 4.2.20 on 2025-04-10 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('translation', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('example_usage', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('knowledge_level', models.IntegerField(default=0)),
            ],
        ),
    ]
